[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
board_build.f_cpu = 80000000L
framework = arduino

; 库依赖
lib_deps =
  SPI
  Wire
  ESP32Async/AsyncTCP
  ESP32Async/ESPAsyncWebServer
  alanswx/ESPAsyncWiFiManager


; 硬件配置
board_build.flash_mode = dio
board_build.filesystem = spiffs


monitor_speed = 115200

; 构建标志
; -Wno-unused-variable / -Wno-unused-function: 忽略未使用变量/函数警告
build_flags =
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -Wno-unused-variable
  -Wno-unused-function
